# Generated by Django 2.2.4 on 2020-12-08 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201208_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='promptCurrent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='befores', to='core.Prompt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='promptNext',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='core.Prompt'),
        ),
    ]
