# Generated by Django 2.2.4 on 2020-12-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201208_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='random',
            field=models.BooleanField(default=True),
        ),
    ]
