# Generated by Django 2.2.4 on 2020-12-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201209_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='random',
        ),
    ]
