# Generated by Django 2.2.4 on 2020-12-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_choice_random'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='promptNext',
        ),
        migrations.AddField(
            model_name='choice',
            name='response',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
