# Generated by Django 2.2.4 on 2020-12-18 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201212_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.Tag'),
        ),
    ]
